version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: medical_db_prod
    restart: always
    environment:
      POSTGRES_DB: medicaldb
      POSTGRES_USER: medicaluser
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5431:5432"   # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    image: kewlima/medical-api:prod
    container_name: medical_api_prod
    restart: always
    depends_on:
      - postgres
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medicaldb
      SPRING_DATASOURCE_USERNAME: medicaluser
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_ENABLED: "true"
    volumes:
      - ./ssl/api-keystore.p12:/app/api-keystore.p12
    ports:
      - "8443:8443"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
