version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_medical
    restart: always
    environment:
      POSTGRES_DB: medical-db-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5431:5432"   # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_medical
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

  app:
    build: .
    container_name: spring_app_medical
    depends_on:
      - postgres
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medical-db-dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_ENABLED: "true"
    ports:
      - "8085:8080"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
