spring:
  datasource:
    url: jdbc:postgresql://72.60.150.221:5431/medical-db-qa
    username: postgres
    password: ${DATABASE_PASSWORD_QA}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT_QA}

#logging:
#  level:
#    root: info
#    org.springframework.web: debug
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace

jwt:
  secret: ${JWT_SECRET}

  access:
    expiration: ${JWT_EXPIRATION:86400000} # 1 dia

  refresh:
    expiration: ${JWT_REFRESH:1209600000} # 14 dias

aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    medical-prefix: medical-storage
    presign-minutes: 10