spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medicaldb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# logging:
#   level:
#     root: info
#     org.springframework.web: debug
#     org.hibernate.SQL: debug
#     org.hibernate.type.descriptor.sql.BasicBinder: trace

jwt:
  secret: pG9qLr5K1e9mB2c8Tq0xD7rN6sYwV4fGmZ1uE0oHjP6nX2tC3lA9vS8kR5dF0bQ

  access:
    expiration: 86400000 # 1 dia

  refresh:
    expiration: 1209600000 # 14 dias

aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}