spring:
  application:
    name: Medical

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /api/v3/api-docs    # adiciona o prefixo /api/
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html  # adiciona o prefixo /api/
    operationsSorter: method
    tagsSorter: alpha